export const products = [
  {
    id: 'agno-ai-studio-template',
    image: '/images/agnoai.webp',
    name: 'Agno AI Studio',
    link: 'https://aurasites.vercel.app/products/agno-ai-studio-template',
    price: 9,
    delay: 'delay-100',
  },
  {
    id: 'paymintx-template',
    image: '/images/paymint.webp',
    name: 'PayMintX',
    link: 'https://aurasites.vercel.app/products/paymintx-template',
    price: 9,
    delay: 'delay-200',
  },
  {
    id: 'opus-devops-template',
    image: '/images/opus.webp',
    name: 'Opus DevOps',
    link: 'https://aurasites.vercel.app/products/opus-devops-template',
    price: 9,
    delay: 'delay-300',
  },
  {
    id: 'ai-saas-marketing-template',
    image: '/images/pollen.webp',
    name: 'AI SaaS Marketing',
    link: "https://aurasites.vercel.app/products/ai-saas-marketing-template",
    price: 29,
    delay: 'delay-400',
  },
  {
    id: 'fiona-designer-portfolio-template',
    image: '/images/fiona.webp',
    name: 'Fiona Designer Portfolio',
    link: "https://aurasites.vercel.app/products/fiona-designer-portfolio-template",
    price: 19,
    delay: 'delay-400',
  },
  {
    id: 'porta-developer-portfolio-template',
    image: '/images/porta.webp',
    name: 'Porta Developer Portfolio',
    link: "https://aurasites.vercel.app/products/porta-developer-portfolio-template",
    price: 0,
    delay: 'delay-500',
  },
];
