# ---- Base Stage ----
FROM oven/bun:1 AS builder

WORKDIR /app

# Copy all source files
COPY . .

# Install dependencies
RUN bun install --frozen-lockfile

# Build Next.js (standalone)
RUN bun run build

# ---- Production Runtime ----
FROM oven/bun:1 AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

# Create non-root user
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs
USER nextjs

# Copy standalone output
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Start standalone server (generated by Next.js)
CMD ["bun", "server.js"]
