// @ts-nocheck -- skip type checking
import * as docs_10 from "../content/docs/creative/scroll.mdx?collection=docs&hash=1742883469340"
import * as docs_9 from "../content/docs/creative/motion-number.mdx?collection=docs&hash=1742883469340"
import * as docs_8 from "../content/docs/creative/globe.mdx?collection=docs&hash=1742883469340"
import * as docs_7 from "../content/docs/chatbot/conversation.mdx?collection=docs&hash=1742883469340"
import * as docs_6 from "../content/docs/chatbot/chatbot-ui.mdx?collection=docs&hash=1742883469340"
import * as docs_5 from "../content/docs/cards/spotlight-cards.mdx?collection=docs&hash=1742883469340"
import * as docs_4 from "../content/docs/cards/product-cards.mdx?collection=docs&hash=1742883469340"
import * as docs_3 from "../content/docs/cards/basic-cards.mdx?collection=docs&hash=1742883469340"
import * as docs_2 from "../content/docs/basic/loaders.mdx?collection=docs&hash=1742883469340"
import * as docs_1 from "../content/docs/basic/buttons.mdx?collection=docs&hash=1742883469340"
import * as docs_0 from "../content/docs/get-started.mdx?collection=docs&hash=1742883469340"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"get-started.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/get-started.mdx"}, data: docs_0 }, { info: {"path":"basic\\buttons.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/basic/buttons.mdx"}, data: docs_1 }, { info: {"path":"basic\\loaders.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/basic/loaders.mdx"}, data: docs_2 }, { info: {"path":"cards\\basic-cards.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/cards/basic-cards.mdx"}, data: docs_3 }, { info: {"path":"cards\\product-cards.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/cards/product-cards.mdx"}, data: docs_4 }, { info: {"path":"cards\\spotlight-cards.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/cards/spotlight-cards.mdx"}, data: docs_5 }, { info: {"path":"chatbot\\chatbot-ui.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/chatbot/chatbot-ui.mdx"}, data: docs_6 }, { info: {"path":"chatbot\\conversation.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/chatbot/conversation.mdx"}, data: docs_7 }, { info: {"path":"creative\\globe.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/creative/globe.mdx"}, data: docs_8 }, { info: {"path":"creative\\motion-number.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/creative/motion-number.mdx"}, data: docs_9 }, { info: {"path":"creative\\scroll.mdx","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/creative/scroll.mdx"}, data: docs_10 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","absolutePath":"D:/My github Repositories/mvpblocks/content/docs/meta.json"}, data: {"pages":["---Guide---","get-started","templates","---Components---","basic","cards","chatbot","creative","marketing"],"root":true} }]);