import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { RootProvider } from "fumadocs-ui/provider";
import { launched } from "@/config/site";
import Prelaunch from "@/components/prelaunch";

const dm = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (launched) {
    <html lang="en" suppressHydrationWarning>
      <body className={`${dm.className}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>;
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dm.className}`}>
        <Prelaunch />
      </body>
    </html>
  );
}
